language: node_js

# By default, gh-pages branch is not built unless you add it to the whitelist
# http://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - gh-pages

before_script:
  - npm install htmlhint

script:
  - htmlhint --config htmlhint.conf index.xhtml
